INSERT INTO `attractions_attraction` (`id`, `name`, `entry_fee`, `opening_hours`, `location`, `accessibility`) VALUES
(1, 'Majorelle Gardens', 70, 'Opening hours: Open daily from 8am to 6pm', 'Rue Yves Saint Laurent, Marrakech', 'Accessible by car and on foot'),
(2, 'Jemaa el-Fna', 0, 'Open 24 hours a day', 'Medina, Marrakech', 'Accessible on foot'),
(3, 'Bahia Palace', 70, 'Open daily from 9am to 5pm', 'Rue Riad Zitoun el Jdid, Marrakech', 'Accessible by car and on foot.'),
(4, 'Koutoubia Mosque', 0, 'Open to non-Muslims only from 9am to 12pm and 2pm to 4pm, except during prayer times', 'Rue el Koutoubia, Marrakech', 'Accessible by car and on foot'),
(5, 'Marrakech Museum', 50, 'Open daily from 9am to 6:30pm', 'Place Ben Youssef, Medina, Marrakech', 'Accessible on foot'),
(6, 'El Badi Palace', 70, 'Open daily from 9am to 5pm', 'Ksibat Nhass, Marrakech', 'Accessible by car and on foot'),
(7, 'Yves Saint Laurent Museum', 100, 'Open daily except Wednesdays, from 10am to 6pm', 'Rue Yves Saint Laurent, Marrakech', 'Accessible by car and on foot'),
(8, 'Menara Gardens', 0, 'Open daily from 8am to 5pm', 'Avenue de la Ménara, Marrakech', 'Accessible by car and on foot'),
(9, 'Maison de la Photographie', 50, 'Opening hours: Open daily from 9:30am to 7pm', '46 Rue Souk Ahal Fassi, Marrakech', 'Accessible on foot within the medina, cars cannot access directly to this location'),
(10, 'Le Jardin Secret', 70, 'Open daily from 9:30am to 5:30pm', 'Rue Mouassine, Medina, Marrakech', 'Accessible on foot within the medina, cars cannot access directly to this location'),
(11, 'Dar Si Said Museum', 40, 'Open daily from 9am to 5pm', 'Riad Zitoun Jdid, Marrakech', 'Accessible on foot within the medina, cars cannot access directly to this location'),
(12, 'Ben Youssef School', 70, 'Open daily from 9am to 5pm', 'Rue Ben Youssef, Medina, Marrakech', 'Accessible on foot.');

INSERT INTO `attractions_hotel` (`id`, `name`, `starting_price`, `location`, `amenities`, `services`, `dining_options`, `pet_policy`) VALUES
(1, 'Royal Mansour Marrakech Hotel', 2000, 'Rue Abou Abbas El Sebti, Marrakech', 'Award-winning spa, pools, Michelin-starred restaurants, tranquil garden', 'Personal butler service, valet parking, free Wi-Fi', 'Several internationally renowned restaurants on-site', 'Pets are not allowed'),
(2, 'Four Seasons Resort Marrakech', 3000, 'Avenue de la Ménara, Marrakech', 'Pools, spa, tennis courts, landscaped gardens', 'Concierge service, free Wi-Fi, shuttle service to the city center', 'Several on-site restaurants offering diverse cuisine', 'Pets are not allowed'),
(3, 'Sofitel Marrakech Lounge & Spa Hotel', 1500, 'Rue Harroun Errachid, Hivernage, Marrakech', 'Spa, outdoor pool, bars, lush gardens', 'Concierge service, free Wi-Fi, on-site parking', 'On-site restaurants offering Moroccan and international cuisine', 'Pets are not allowed'),
(4, 'Es Saadi Marrakech Resort - Palace Hotel', 2500, 'Avenue El Quadissia, Hivernage, Marrakech', 'Pools, spa, casino, tennis courts, lush gardens', 'Concierge service, free Wi-Fi, shuttle service to the city center', 'Several on-site restaurants offering diverse cuisine', 'Pets are not allowed'),
(5, 'Riad Kniza Hotel', 1500, '34 Derb l\'Hôtel, Bab Doukala, Marrakech', 'Patio with fountain, terrace with panoramic view, spa, restaurant', 'Concierge service, free Wi-Fi, airport shuttle service', 'On-site restaurant offering traditional Moroccan cuisine', 'Pets are not allowed'),
(6, 'Les Jardins de la Koutoubia Hotel', 1800, '26 Rue de la Koutoubia, Marrakech', 'Outdoor pool, spa, restaurant, rooftop terrace with Medina view', 'Concierge service, free Wi-Fi, valet parking', 'Several on-site restaurants offering international and Moroccan cuisine', 'Pets are not allowed'),
(7, 'La Sultana Marrakech Hotel', 2500, '403 Rue de la Kasbah, Marrakech', 'Pools, spa, hammam, restaurant, terrace with Medina view', 'Concierge service, free Wi-Fi, airport shuttle service', 'Several on-site restaurants offering Moroccan and international cuisine', 'Pets are not allowed'),
(8, 'Riad Les Yeux Bleus Hotel', 800, '84 Derb Sidi Ahmed Soussi, Marrakech', 'Patio with fountain, terrace with Medina view, massage lounge', 'Concierge service, free Wi-Fi, airport transfer', 'Breakfast included, Moroccan cuisine dinner upon request', 'Pets are not allowed'),
(9, 'Riad Farnatchi Hotel', 2500, '2 Derb Farnatchi, Marrakech', 'Patio with pool, spa, restaurant, tea room', 'Concierge service, free Wi-Fi, airport shuttle service', 'Breakfast included, Moroccan and international cuisine dinner upon request', 'Pets are not allowed'),
(10, 'Riad Joya Hotel', 1500, '8 Derb El Hammam, Mouassine, Marrakech', 'Patio with fountain, terrace with panoramic view, massage lounge', 'Concierge service, free Wi-Fi, airport transfer', 'Breakfast included, Moroccan and international cuisine dinner upon request', 'Pets may be accepted upon prior request'),
(11, 'Riad Dar Anika Hotel', 1800, '112-113 Rue Riad Zitoun Kedim, Marrakech', 'Patio with pool, spa, restaurant, tea room', 'Concierge service, free Wi-Fi, airport shuttle service', 'Breakfast included, Moroccan and international cuisine dinner upon request', 'Pets may be accepted upon prior request'),
(12, 'Riad Palais Sebban Hotel', 1000, '43 Derb Moulay Abdellah Ben Hussein, Marrakech', 'Patio with fountain, pool, restaurant, massage lounge', 'Concierge service, free Wi-Fi, airport transfer', 'Breakfast included, Moroccan and international cuisine dinner upon request', 'Pets may be accepted upon prior request');

INSERT INTO `attractions_restaurant` (`id`, `name`, `opening_hours`, `has_alcohol`, `price_range`, `Atmosphere`, `parking`, `reservation`, `accessibility`, `location`, `cuisine`) VALUES
(2, 'Dar Moha', '12pm to 3pm and 7pm to 11pm', 1, '$$', 'Chic and romantic, with an intimate atmosphere', 0, 'Recommended', 'Accessible on foot within the medina', '81 Rue Dar El Bacha, Marrakech', 'Moroccan and international'),
(3, 'La Trattoria', '12pm to 3pm and 7pm to 11pm', 1, '$', 'Warm and family-friendly, with authentic Italian atmosphere', 1, 'Recommended', 'Accessible by car', '137 Rue Mohammed el Beqal, Marrakech', 'Italian'),
(4, 'Le Thai', '7pm to 11pm', 1, '$', 'Exotic and colorful, with authentic Thai atmosphere', 1, 'Recommended', 'Accessible by car', 'Avenue Echouhada, Hivernage, Marrakech', 'Thai'),
(5, 'Toro Toro', '7pm to 11pm', 1, '$$', 'Elegant and vibrant, with modern Latin American atmosphere', 1, 'Recommended', 'Accessible by car', 'Avenue Echouhada, Hivernage, Marrakech', 'Latin American'),
(6, 'Le Comptoir Darna', '7pm to 2am', 1, '$$', 'Festive and lively, with belly dance and live music performances', 1, 'Recommended', 'Accessible by car', 'Avenue Echouhada, Hivernage, Marrakech', 'Avenue Echouhada, Hivernage, Marrakech'),
(7, 'Bo & Zin', '7pm to 2am', 1, '$$', 'Chic and glamorous, with lounge atmosphere and DJs', 1, 'Recommended', 'Accessible by car', 'Route de l\'Ourika, Km 3.5, Marrakech', 'International fusion with Moroccan touches'),
(8, 'Al Fassia', '12pm to 3pm and 7pm to 11pm', 0, '$$', 'Traditional and family-friendly, with a cozy atmosphere', 1, 'Recommended', 'Accessible by car', '55 Boulevard Zerktouni, Marrakech', 'Moroccan'),
(9, 'Jad Mahal', '7pm to 2am', 1, '$$', 'Luxurious and vibrant, with dance and live music performances', 1, 'Recommended', 'Accessible by car', 'Avenue Echouhada, Hivernage, Marrakech', 'Moroccan and international fusion with Asian influences'),
(10, 'La Table du Riad', '12pm to 3pm and 7pm to 11pm', 1, '$', 'Warm and authentic, with traditional riad atmosphere', 0, 'Recommended', 'Accessible by foot in the Medina', '29 Derb Tizougarine, Bab Doukkala, Marrakech', 'Moroccan and international'),
(11, 'Dar Yacout', '7pm to 11pm', 0, '$$$', 'Elegant and refined, with traditional Moroccan atmosphere', 0, 'Required', 'Accessible by foot in the Medina', '79 Sidi Ahmed Soussi, Bab Doukkala, Marrakech', 'Moroccan'),
(12, 'Dar Zellij', '12pm to 3pm and 7pm to 11pm', 0, '$$', 'Traditional and authentic, with a patio decorated with mosaics and zelliges', 0, 'Recommended', 'Accessible by foot in the Medina', '1 Kaasour, Sidi Ben Slimane, Marrakech', 'Moroccan'),
(13, 'Le Bistrot Romain', '12pm to 3pm and 7pm to 11pm', 1, '$', 'Friendly and casual, with warm atmosphere and rustic Italian décor', 1, 'Recommended', 'Accessible by car', 'Gueliz, Rue de Yougoslavie, Marrakech', 'Italian');