# Generated by Django 5.0.4 on 2024-04-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
