# Generated by Django 5.0.4 on 2024-04-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_attraction_hotel_restaurant_delete_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='has_alcohol',
            field=models.BooleanField(default=False),
        ),
    ]
