# Generated by Django 5.0.4 on 2024-04-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0005_restaurant_has_alcohol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='vibe',
            new_name='Atmosphere',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='parking',
            field=models.BooleanField(default=False),
        ),
    ]
