# Generated by Django 5.0.4 on 2024-04-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0006_rename_vibe_restaurant_atmosphere_restaurant_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='starting_price',
            field=models.IntegerField(default=0),
        ),
    ]
